### ISSUE TITLE
Allow for specification of output file or directory

### ISSUE THREAD

**Issue by joelnitta** [WEHI-ResearchComputing/CarpentriesSlides#10]
I keep my slides in a different directory that the lesson directory, so I'd like to be able to save the slides elsewhere.

Example code:

```
CarpentriesSlides::make_md("~/repos/shell-novice", md = "~/repos/shell-slides/slides.md")
```

**Comment by multimeric** [comment]
I originally had it work like that, but changed it for simplicity. 

How about an API where each function returns the output path, which is auto generated if not provided?

```R
make_md(repo)
# "~/repos/shell-novice/slides.md"
make_md(repo, output = "~/repos/shell-slides/slides.md")
# "~/repos/shell-slides/slides.md"
```

**Comment by joelnitta** [comment]
Sure, I like returning the output path (for use with {targets}, actually...)
